version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - guardian-daemon-net
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  guardian-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guardian-daemon
    depends_on:
      - mosquitto
    restart: unless-stopped
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    links:
      - mosquitto
    volumes:
      - ./logs:/app/logs
    networks:
      - guardian-daemon-net
    ports:
      - "5000:5000"

networks:
  guardian-daemon-net:
    driver: bridge
